### ISSUE TITLE
Expose parts for #lhs and #rhs

### ISSUE THREAD

**Issue by bennypowers** [PolymerLabs/playground-elements#199]
If `#lhs` and `#rhs` had parts, users could write custom layouts while still using `<playground-ide>`. For example, a vertical layout would be:

```scss
playground-ide {
  display: flex;
  flex-flow: row wrap;
  &::part(editor) {
    width: 100%;
    height: 75%;
  }
  &::part(preview) {
    width: 100%;
    height: 25%;
  }
}
```
