### ISSUE TITLE
Resize code preview

### ISSUE THREAD

**Issue by e111077** [PolymerLabs/playground-elements#60]
It would be cool if the user could click drag the divider to resize the preview / editor otherwise, simply expose a custom prop e.g.

```css
code-sample-editor {width: var(--code-sample-editor-width, 70%);}
code-sample-preview {width: calc(100% - var(--code-sample-editor-width, 70%));}
```
